error
RECIEVED FOLLOWING ERROR ON LINE 37:
Traceback (most recent call last):
  File "C:\Users\saman\Desktop\Required-Drills\PyDrill_185.py", line 37, in <module>
    cur.execute("fileList")
sqlite3.OperationalError: near "fileList": syntax error